// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.6.1
// source: chat2.proto

package chat

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ResponseNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cantidad1   int64  `protobuf:"varint,1,opt,name=Cantidad1,proto3" json:"Cantidad1,omitempty"`
	Cantidad2   int64  `protobuf:"varint,2,opt,name=Cantidad2,proto3" json:"Cantidad2,omitempty"`
	Cantidad3   int64  `protobuf:"varint,3,opt,name=Cantidad3,proto3" json:"Cantidad3,omitempty"`
	NombreLibro string `protobuf:"bytes,4,opt,name=NombreLibro,proto3" json:"NombreLibro,omitempty"`
}

func (x *ResponseNode) Reset() {
	*x = ResponseNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseNode) ProtoMessage() {}

func (x *ResponseNode) ProtoReflect() protoreflect.Message {
	mi := &file_chat2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseNode.ProtoReflect.Descriptor instead.
func (*ResponseNode) Descriptor() ([]byte, []int) {
	return file_chat2_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseNode) GetCantidad1() int64 {
	if x != nil {
		return x.Cantidad1
	}
	return 0
}

func (x *ResponseNode) GetCantidad2() int64 {
	if x != nil {
		return x.Cantidad2
	}
	return 0
}

func (x *ResponseNode) GetCantidad3() int64 {
	if x != nil {
		return x.Cantidad3
	}
	return 0
}

func (x *ResponseNode) GetNombreLibro() string {
	if x != nil {
		return x.NombreLibro
	}
	return ""
}

type MessageNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cantidad1   int64  `protobuf:"varint,1,opt,name=Cantidad1,proto3" json:"Cantidad1,omitempty"`
	Cantidad2   int64  `protobuf:"varint,2,opt,name=Cantidad2,proto3" json:"Cantidad2,omitempty"`
	Cantidad3   int64  `protobuf:"varint,3,opt,name=Cantidad3,proto3" json:"Cantidad3,omitempty"`
	NombreLibro string `protobuf:"bytes,4,opt,name=NombreLibro,proto3" json:"NombreLibro,omitempty"`
	ID          int64  `protobuf:"varint,5,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *MessageNode) Reset() {
	*x = MessageNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageNode) ProtoMessage() {}

func (x *MessageNode) ProtoReflect() protoreflect.Message {
	mi := &file_chat2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageNode.ProtoReflect.Descriptor instead.
func (*MessageNode) Descriptor() ([]byte, []int) {
	return file_chat2_proto_rawDescGZIP(), []int{1}
}

func (x *MessageNode) GetCantidad1() int64 {
	if x != nil {
		return x.Cantidad1
	}
	return 0
}

func (x *MessageNode) GetCantidad2() int64 {
	if x != nil {
		return x.Cantidad2
	}
	return 0
}

func (x *MessageNode) GetCantidad3() int64 {
	if x != nil {
		return x.Cantidad3
	}
	return 0
}

func (x *MessageNode) GetNombreLibro() string {
	if x != nil {
		return x.NombreLibro
	}
	return ""
}

func (x *MessageNode) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type MessagePropuesta2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cantidad1   int64  `protobuf:"varint,1,opt,name=Cantidad1,proto3" json:"Cantidad1,omitempty"`
	Cantidad2   int64  `protobuf:"varint,2,opt,name=Cantidad2,proto3" json:"Cantidad2,omitempty"`
	Cantidad3   int64  `protobuf:"varint,3,opt,name=Cantidad3,proto3" json:"Cantidad3,omitempty"`
	NombreLibro string `protobuf:"bytes,4,opt,name=NombreLibro,proto3" json:"NombreLibro,omitempty"`
	ID          int64  `protobuf:"varint,5,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *MessagePropuesta2) Reset() {
	*x = MessagePropuesta2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat2_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessagePropuesta2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePropuesta2) ProtoMessage() {}

func (x *MessagePropuesta2) ProtoReflect() protoreflect.Message {
	mi := &file_chat2_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePropuesta2.ProtoReflect.Descriptor instead.
func (*MessagePropuesta2) Descriptor() ([]byte, []int) {
	return file_chat2_proto_rawDescGZIP(), []int{2}
}

func (x *MessagePropuesta2) GetCantidad1() int64 {
	if x != nil {
		return x.Cantidad1
	}
	return 0
}

func (x *MessagePropuesta2) GetCantidad2() int64 {
	if x != nil {
		return x.Cantidad2
	}
	return 0
}

func (x *MessagePropuesta2) GetCantidad3() int64 {
	if x != nil {
		return x.Cantidad3
	}
	return 0
}

func (x *MessagePropuesta2) GetNombreLibro() string {
	if x != nil {
		return x.NombreLibro
	}
	return ""
}

func (x *MessagePropuesta2) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type ResponseNameNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok int64 `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
}

func (x *ResponseNameNode) Reset() {
	*x = ResponseNameNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat2_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseNameNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseNameNode) ProtoMessage() {}

func (x *ResponseNameNode) ProtoReflect() protoreflect.Message {
	mi := &file_chat2_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseNameNode.ProtoReflect.Descriptor instead.
func (*ResponseNameNode) Descriptor() ([]byte, []int) {
	return file_chat2_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseNameNode) GetOk() int64 {
	if x != nil {
		return x.Ok
	}
	return 0
}

type ResponseCatalago struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListaLibros []string `protobuf:"bytes,1,rep,name=ListaLibros,proto3" json:"ListaLibros,omitempty"`
}

func (x *ResponseCatalago) Reset() {
	*x = ResponseCatalago{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat2_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseCatalago) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCatalago) ProtoMessage() {}

func (x *ResponseCatalago) ProtoReflect() protoreflect.Message {
	mi := &file_chat2_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCatalago.ProtoReflect.Descriptor instead.
func (*ResponseCatalago) Descriptor() ([]byte, []int) {
	return file_chat2_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseCatalago) GetListaLibros() []string {
	if x != nil {
		return x.ListaLibros
	}
	return nil
}

type EstadoE2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estado int64 `protobuf:"varint,1,opt,name=Estado,proto3" json:"Estado,omitempty"`
}

func (x *EstadoE2) Reset() {
	*x = EstadoE2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat2_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstadoE2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadoE2) ProtoMessage() {}

func (x *EstadoE2) ProtoReflect() protoreflect.Message {
	mi := &file_chat2_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadoE2.ProtoReflect.Descriptor instead.
func (*EstadoE2) Descriptor() ([]byte, []int) {
	return file_chat2_proto_rawDescGZIP(), []int{5}
}

func (x *EstadoE2) GetEstado() int64 {
	if x != nil {
		return x.Estado
	}
	return 0
}

type EstadoS2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estado int64 `protobuf:"varint,1,opt,name=Estado,proto3" json:"Estado,omitempty"`
}

func (x *EstadoS2) Reset() {
	*x = EstadoS2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat2_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstadoS2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadoS2) ProtoMessage() {}

func (x *EstadoS2) ProtoReflect() protoreflect.Message {
	mi := &file_chat2_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadoS2.ProtoReflect.Descriptor instead.
func (*EstadoS2) Descriptor() ([]byte, []int) {
	return file_chat2_proto_rawDescGZIP(), []int{6}
}

func (x *EstadoS2) GetEstado() int64 {
	if x != nil {
		return x.Estado
	}
	return 0
}

type ResponseChunks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListaIPS []string `protobuf:"bytes,1,rep,name=ListaIPS,proto3" json:"ListaIPS,omitempty"`
}

func (x *ResponseChunks) Reset() {
	*x = ResponseChunks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat2_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseChunks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseChunks) ProtoMessage() {}

func (x *ResponseChunks) ProtoReflect() protoreflect.Message {
	mi := &file_chat2_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseChunks.ProtoReflect.Descriptor instead.
func (*ResponseChunks) Descriptor() ([]byte, []int) {
	return file_chat2_proto_rawDescGZIP(), []int{7}
}

func (x *ResponseChunks) GetListaIPS() []string {
	if x != nil {
		return x.ListaIPS
	}
	return nil
}

var File_chat2_proto protoreflect.FileDescriptor

var file_chat2_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x68, 0x61, 0x74, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63,
	0x68, 0x61, 0x74, 0x22, 0x8a, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x4e, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64,
	0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x43, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61,
	0x64, 0x31, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x32, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x43, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x32,
	0x12, 0x1c, 0x0a, 0x09, 0x43, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x33, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x43, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x33, 0x12, 0x20,
	0x0a, 0x0b, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x4c, 0x69, 0x62, 0x72, 0x6f, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x4c, 0x69, 0x62, 0x72, 0x6f,
	0x22, 0x99, 0x01, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x43, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x31, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x43, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x31, 0x12, 0x1c,
	0x0a, 0x09, 0x43, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x43, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x32, 0x12, 0x1c, 0x0a, 0x09,
	0x43, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x43, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x33, 0x12, 0x20, 0x0a, 0x0b, 0x4e, 0x6f,
	0x6d, 0x62, 0x72, 0x65, 0x4c, 0x69, 0x62, 0x72, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x4c, 0x69, 0x62, 0x72, 0x6f, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x22, 0x9f, 0x01, 0x0a,
	0x11, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x75, 0x65, 0x73, 0x74,
	0x61, 0x32, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x31, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x43, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x31,
	0x12, 0x1c, 0x0a, 0x09, 0x43, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x32, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x43, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x32, 0x12, 0x1c,
	0x0a, 0x09, 0x43, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x43, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x33, 0x12, 0x20, 0x0a, 0x0b,
	0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x4c, 0x69, 0x62, 0x72, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x4c, 0x69, 0x62, 0x72, 0x6f, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x22, 0x22,
	0x0a, 0x10, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f,
	0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x4f, 0x6b, 0x22, 0x34, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x61,
	0x74, 0x61, 0x6c, 0x61, 0x67, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x4c,
	0x69, 0x62, 0x72, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x4c, 0x69, 0x73,
	0x74, 0x61, 0x4c, 0x69, 0x62, 0x72, 0x6f, 0x73, 0x22, 0x22, 0x0a, 0x08, 0x45, 0x73, 0x74, 0x61,
	0x64, 0x6f, 0x45, 0x32, 0x12, 0x16, 0x0a, 0x06, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x22, 0x22, 0x0a, 0x08,
	0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x53, 0x32, 0x12, 0x16, 0x0a, 0x06, 0x45, 0x73, 0x74, 0x61,
	0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f,
	0x22, 0x2c, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x68, 0x75, 0x6e,
	0x6b, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x49, 0x50, 0x53, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x49, 0x50, 0x53, 0x32, 0xba,
	0x02, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x32, 0x12,
	0x34, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x12, 0x11, 0x2e, 0x63,
	0x68, 0x61, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x1a,
	0x12, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x70, 0x75, 0x65, 0x73,
	0x74, 0x61, 0x44, 0x12, 0x17, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x32, 0x1a, 0x16, 0x2e, 0x63,
	0x68, 0x61, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x4e, 0x6f, 0x64, 0x65, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0f, 0x4d, 0x6f, 0x73, 0x74, 0x72, 0x61,
	0x72, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x6f, 0x12, 0x16, 0x2e, 0x63, 0x68, 0x61, 0x74,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64,
	0x65, 0x1a, 0x16, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x61, 0x67, 0x6f, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x0f, 0x42,
	0x6f, 0x72, 0x72, 0x61, 0x72, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x6f, 0x73, 0x32, 0x12, 0x0e,
	0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x45, 0x32, 0x1a, 0x0e,
	0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x53, 0x32, 0x22, 0x00,
	0x12, 0x39, 0x0a, 0x0c, 0x42, 0x75, 0x73, 0x63, 0x61, 0x72, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73,
	0x12, 0x11, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x1a, 0x14, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_chat2_proto_rawDescOnce sync.Once
	file_chat2_proto_rawDescData = file_chat2_proto_rawDesc
)

func file_chat2_proto_rawDescGZIP() []byte {
	file_chat2_proto_rawDescOnce.Do(func() {
		file_chat2_proto_rawDescData = protoimpl.X.CompressGZIP(file_chat2_proto_rawDescData)
	})
	return file_chat2_proto_rawDescData
}

var file_chat2_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_chat2_proto_goTypes = []interface{}{
	(*ResponseNode)(nil),      // 0: chat.ResponseNode
	(*MessageNode)(nil),       // 1: chat.MessageNode
	(*MessagePropuesta2)(nil), // 2: chat.MessagePropuesta2
	(*ResponseNameNode)(nil),  // 3: chat.ResponseNameNode
	(*ResponseCatalago)(nil),  // 4: chat.ResponseCatalago
	(*EstadoE2)(nil),          // 5: chat.EstadoE2
	(*EstadoS2)(nil),          // 6: chat.EstadoS2
	(*ResponseChunks)(nil),    // 7: chat.ResponseChunks
}
var file_chat2_proto_depIdxs = []int32{
	1, // 0: chat.ChatService2.Propuesta:input_type -> chat.MessageNode
	2, // 1: chat.ChatService2.PropuestaD:input_type -> chat.MessagePropuesta2
	3, // 2: chat.ChatService2.MostrarCatalogo:input_type -> chat.ResponseNameNode
	5, // 3: chat.ChatService2.BorrarArchivos2:input_type -> chat.EstadoE2
	1, // 4: chat.ChatService2.BuscarChunks:input_type -> chat.MessageNode
	0, // 5: chat.ChatService2.Propuesta:output_type -> chat.ResponseNode
	3, // 6: chat.ChatService2.PropuestaD:output_type -> chat.ResponseNameNode
	4, // 7: chat.ChatService2.MostrarCatalogo:output_type -> chat.ResponseCatalago
	6, // 8: chat.ChatService2.BorrarArchivos2:output_type -> chat.EstadoS2
	7, // 9: chat.ChatService2.BuscarChunks:output_type -> chat.ResponseChunks
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chat2_proto_init() }
func file_chat2_proto_init() {
	if File_chat2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chat2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat2_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessagePropuesta2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat2_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseNameNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat2_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseCatalago); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat2_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EstadoE2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat2_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EstadoS2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat2_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseChunks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chat2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat2_proto_goTypes,
		DependencyIndexes: file_chat2_proto_depIdxs,
		MessageInfos:      file_chat2_proto_msgTypes,
	}.Build()
	File_chat2_proto = out.File
	file_chat2_proto_rawDesc = nil
	file_chat2_proto_goTypes = nil
	file_chat2_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ChatService2Client is the client API for ChatService2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatService2Client interface {
	Propuesta(ctx context.Context, in *MessageNode, opts ...grpc.CallOption) (*ResponseNode, error)
	PropuestaD(ctx context.Context, in *MessagePropuesta2, opts ...grpc.CallOption) (*ResponseNameNode, error)
	MostrarCatalogo(ctx context.Context, in *ResponseNameNode, opts ...grpc.CallOption) (*ResponseCatalago, error)
	BorrarArchivos2(ctx context.Context, in *EstadoE2, opts ...grpc.CallOption) (*EstadoS2, error)
	BuscarChunks(ctx context.Context, in *MessageNode, opts ...grpc.CallOption) (*ResponseChunks, error)
}

type chatService2Client struct {
	cc grpc.ClientConnInterface
}

func NewChatService2Client(cc grpc.ClientConnInterface) ChatService2Client {
	return &chatService2Client{cc}
}

func (c *chatService2Client) Propuesta(ctx context.Context, in *MessageNode, opts ...grpc.CallOption) (*ResponseNode, error) {
	out := new(ResponseNode)
	err := c.cc.Invoke(ctx, "/chat.ChatService2/Propuesta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatService2Client) PropuestaD(ctx context.Context, in *MessagePropuesta2, opts ...grpc.CallOption) (*ResponseNameNode, error) {
	out := new(ResponseNameNode)
	err := c.cc.Invoke(ctx, "/chat.ChatService2/PropuestaD", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatService2Client) MostrarCatalogo(ctx context.Context, in *ResponseNameNode, opts ...grpc.CallOption) (*ResponseCatalago, error) {
	out := new(ResponseCatalago)
	err := c.cc.Invoke(ctx, "/chat.ChatService2/MostrarCatalogo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatService2Client) BorrarArchivos2(ctx context.Context, in *EstadoE2, opts ...grpc.CallOption) (*EstadoS2, error) {
	out := new(EstadoS2)
	err := c.cc.Invoke(ctx, "/chat.ChatService2/BorrarArchivos2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatService2Client) BuscarChunks(ctx context.Context, in *MessageNode, opts ...grpc.CallOption) (*ResponseChunks, error) {
	out := new(ResponseChunks)
	err := c.cc.Invoke(ctx, "/chat.ChatService2/BuscarChunks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatService2Server is the server API for ChatService2 service.
type ChatService2Server interface {
	Propuesta(context.Context, *MessageNode) (*ResponseNode, error)
	PropuestaD(context.Context, *MessagePropuesta2) (*ResponseNameNode, error)
	MostrarCatalogo(context.Context, *ResponseNameNode) (*ResponseCatalago, error)
	BorrarArchivos2(context.Context, *EstadoE2) (*EstadoS2, error)
	BuscarChunks(context.Context, *MessageNode) (*ResponseChunks, error)
}

// UnimplementedChatService2Server can be embedded to have forward compatible implementations.
type UnimplementedChatService2Server struct {
}

func (*UnimplementedChatService2Server) Propuesta(context.Context, *MessageNode) (*ResponseNode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Propuesta not implemented")
}
func (*UnimplementedChatService2Server) PropuestaD(context.Context, *MessagePropuesta2) (*ResponseNameNode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PropuestaD not implemented")
}
func (*UnimplementedChatService2Server) MostrarCatalogo(context.Context, *ResponseNameNode) (*ResponseCatalago, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MostrarCatalogo not implemented")
}
func (*UnimplementedChatService2Server) BorrarArchivos2(context.Context, *EstadoE2) (*EstadoS2, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BorrarArchivos2 not implemented")
}
func (*UnimplementedChatService2Server) BuscarChunks(context.Context, *MessageNode) (*ResponseChunks, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuscarChunks not implemented")
}

func RegisterChatService2Server(s *grpc.Server, srv ChatService2Server) {
	s.RegisterService(&_ChatService2_serviceDesc, srv)
}

func _ChatService2_Propuesta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageNode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatService2Server).Propuesta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService2/Propuesta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatService2Server).Propuesta(ctx, req.(*MessageNode))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService2_PropuestaD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessagePropuesta2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatService2Server).PropuestaD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService2/PropuestaD",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatService2Server).PropuestaD(ctx, req.(*MessagePropuesta2))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService2_MostrarCatalogo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResponseNameNode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatService2Server).MostrarCatalogo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService2/MostrarCatalogo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatService2Server).MostrarCatalogo(ctx, req.(*ResponseNameNode))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService2_BorrarArchivos2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstadoE2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatService2Server).BorrarArchivos2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService2/BorrarArchivos2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatService2Server).BorrarArchivos2(ctx, req.(*EstadoE2))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService2_BuscarChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageNode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatService2Server).BuscarChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService2/BuscarChunks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatService2Server).BuscarChunks(ctx, req.(*MessageNode))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChatService2_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chat.ChatService2",
	HandlerType: (*ChatService2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Propuesta",
			Handler:    _ChatService2_Propuesta_Handler,
		},
		{
			MethodName: "PropuestaD",
			Handler:    _ChatService2_PropuestaD_Handler,
		},
		{
			MethodName: "MostrarCatalogo",
			Handler:    _ChatService2_MostrarCatalogo_Handler,
		},
		{
			MethodName: "BorrarArchivos2",
			Handler:    _ChatService2_BorrarArchivos2_Handler,
		},
		{
			MethodName: "BuscarChunks",
			Handler:    _ChatService2_BuscarChunks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat2.proto",
}
